### ISSUE TITLE
Introduce support for scheduling N tasks based on iterable

### ISSUE THREAD

**Issue by fridex** [fridex/selinon#5]
Currently, there is no way how to define a flow which would spawn N tasks based on iterable. A use case:

I want to spawn *N-times* Task2 based on results of Task1. The YAML configuration could be:

```yaml
flow-definition:
  - name: flow1
    edges:
      - from:
        to: Task1
      - from: Task1
        to: Task2
        condition:
          name: 'cond1'
        foreach:
          iterable: result # or node_args
          condition:
            name: cond2
            args:
             - foo
             - bar
```
Semantics:

When flow1 is started, Task1 is scheduled (condition is always true). When Task1 finishes, N tasks of type Task2 are scheduled so that:
  1. First, there is evaluated condition 'cond1'.
  2. If cond1 is false, do not proceed, otherwise:
  3. For each result (or node_args) evaluate condition 'cond2' with `result['foo']['bar'][i]` (or `node_args['foo']['bar'][i]`) like:

  ```python
if cond1():
      for item in node_args['foo']['bar']:
         if cond2(item):
           Task2().apply_async(node_args)
   ```

This way, we can define flows which would look like:

```
flow1:
                                       |
                                     Task1
                                       |
    -----------------------------------------------------------------------
    |                |                 |                                  | 
  Task2            Task2             Task2                 ...            Task2
```
